[package]
name = "dotman"
version = "0.1.0"
authors = ["João Marcos <marcospb19@hotmail.com>"]
repository = "https://github.com/marcospb19/dotman"
edition = "2018"

[dependencies]
clap = {version = "~2.27.0", features = ["wrap_help"]}
